### ISSUE TITLE
Esc key from inside of vim in terminal does not escape.

### ISSUE THREAD

**Issue by sstern6** [play-with-docker/play-with-kubernetes.github.io#24] opened 2018-05-01 22:31 UTC
When escaping after editing a file in vim, the escape isnt escaping to allow you to save.

https://github.com/docker/labs/issues/409#event-1604175610

**Comment by ManoMarks** [comment] 2018-05-07 17:54
I'm unable to reproduce. Can you supply the following information?

* The browser and version you're using
* Your base operating system

**Comment by ManoMarks** [comment] 2018-05-15 18:05
Closing as there was no more information to replicate

**Closed by ManoMarks** 2018-05-15 18:05 UTC
